### ISSUE TITLE
Generator doesn't work

### ISSUE THREAD

**Issue by View12138** [CollinAlpert/Lombok.NET#9]
When I use any `QualifiedNameSyntax` , the generator doesn't work, 
e.g. [Lombok.NET.NoArgsConstructor] or [NET.NoArgsConstructor]

**Comment by CollinAlpert** [comment]
The fix is released in v1.2.1.

**Comment by View12138** [comment]
I'm so sorry, my PR still hasn't fixed this bug, the [Lombok.NET.NoArgsConstructor] still doesn't generted my code.
(And I can't debugging the genertor when I develop. How can I debugging this libraries ?)

**Comment by CollinAlpert** [comment]
Debugging is described [here](https://github.com/CollinAlpert/Lombok.NET#building-and-debugging).
I have released v1.2.2 which should fix the behavior.

**Comment by View12138** [comment]
Thank you so match!
(This repository is very nice for Java developer!)

**Comment by CollinAlpert** [comment]
I'm happy to hear that. Let me know if you have any other issues or feature requests!
